services:
  - type: web
    name: sl-manish1671
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SKILLENS_DEMO_PASSWORD
        sync: false
